at91bootstrap: fix building with gcc-8
Make sure that no builtins are used. Otherwise building may fail with:

[...]/bin/ld: string.o: in function `memcpy':
[...]/Bootstrap-v1.16/board/at91sam9261ek/dataflash/../../../lib/string.c:27: undefined reference to `memmove'
collect2: error: ld returned 1 exit status

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>